Map<String, String> translateArabic = {
  "title": "راصد الحلقات",
  "logout": "تسجيل خروج",
  "please_wait": " الرجاء الانتظار ...",
  "sign_in": "تسجيل دخول",
  "email": "البريد الإلكتروني",
  "email_error": "البريد الإلكتروني خاطئ",
  "enter_email": "أدخل البريد الاكتروني",
  "password": "كلمة المرور",
  "enter_password": "أدخل كلمة المرور",
  "welcome_back": "أهلا بعودتك",
  "forgot_password": "نسيت كلمة المرور؟",
  "use_password": "استخدام كلمة المرور",
  "error_connect_to_netwotk": "لا يوجد اتصال بالانترنت",
  "error_connect_to_server": "مشكله في الاتصال بالسيرفر",
  "url_connect_be_found": "اممم... هذه الصفحة غير موجودة.",
  "name": "الاسم",
  "enter_name": "أدخل الاسم",
  "phone": "رقم الجوال",
  "enter_phone": "أدخل رقم الجوال",
  "construction": "إنشاء",
  "sign_up": "بــ  تسجيل الدخول",
  "add": "إضافة",
  "save_changed": "حفظ التغيرات",
  "identification_number_location": "رقم الهوية / الاقامة",
  "enter_identification_number_location": "أدخل رقم الهوية / الاقامة",
  "episode_list": "قائمة الحلقات",
  "maknoon": "مكنون",
  "synchronization": "مزامنة البيانات",
  "suggestions_and_complaints": "المقترحات و الشكاوي",
  "about_as": "من نحن",
  "draft": "حاضر",
  "done": "اكمل",
  "follow_up": "المتابعة",
  "listen": "الحفظ",
  "reviewsmall": "المراجعة الصغرى",
  "reviewbig": "المراجعة الكبرى",
  "tlawa": "التلاوة",
  "quran": "المصحف",
  "from_sura": "من سورة",
  "from_aya": "من آية",
  "to_sura": "إلى سورة",
  "to_aya": "إلى آية",
  "course": "المقرر",
  "Notes": "الملاحظات",
  "save_errors": "أخطاء الحفظ",
  "preservation_quality": "جودة الحفظ",
  "intonation_errors": "أخطاء التجويد",
  "date_planned": "تاريخ الأستحقاق",
  "actual_date": "تاريخ التسليم",
  "difference_date": "الفرق",
  "day": "يوم",
  "enter_number": "ادخل الرقم",
  "save": "حفظ",
  "can_not_yong_surh": "لا يمكن اختيار سورة ترتيبها أسفل",
  "can_not_up_surh": "لا يمكن اختيار سورة ترتيبها أعلى",
  "can_not_bottom_aya": "لا يمكن اختيار اية ترتيبها أسفل",
  "can_not_up_aya": "لا يمكن اختيار اية ترتيبها أعلى",
  "warring": "تنبيه",
  "ok_add_listen_line": "تم حفظ البيانات بنجاح",
  "error_add_listen_line": "هناك مشكلة في إضافة مقرر",
  "behaviour": "السلوك",
  "behaviour_student": "إضافة سلوك للطالب",
  "note_behaviour_student": "ملاحظات السلوك السابقة",
  "select_behaviour": "اختر سلوك",
  "do_you_want_to_send_the_behavior": "هل تريد إرسال السلوك",
  "inform_the_parent_of_the_behavior": "ابلاغ ولي الامر بالسلوك",
  "send_the_behavior_to_the_episode_moderator": "إرسال السلوك لمشرف الحلقة",
  "yes": "نعم",
  "no": "لا",
  "confirm": "تاكيد",
  "ok_add_behavior": "تم إضافة السلوك بنجاح",
  "error_add_behavior": "هناك مشكلة في إضافة سلوك",
  "there_is_no_notes": "لاتوجد ملاحظات",
  "there_is_no_notifications": "لاتوجد اشعارات",
  "notification_details": "تفاصيل الاشعار",
  "notification_date": "تاريخ الاشعار",
  "ok": "موافق",
  "subject_of_complaint": "موضوع الشكوى",
  "complaint_details": "تفاصيل الشكوى",
  "enter_subject": "ادخل موضوع الشكوى",
  "enter_details": "ادخل تفاصيل الشكوى",
  "studentـnomination": "ترشيح طالب",
  "select_period": "اختر فتره",
  "select_center": "اختر مركز",
  "there_is_no_calendarCenter": "لا توجد جداول للاختبارات",
  "center_test": "مركز الاختبار",
  "type": "النوع",
  "path": "المسار",
  "branch": "الفرع",
  "error_get_branches": "هناك مشكلة في تحميل الفروع",
  "registration": "تسجيل",
  "unregister": "إلغاء تسجيل",
  "ok_registration": "تم التسجيل بنجاح",
  "ok_unregister": "تم إلغاء التسجيل بنجاح",
  "error_registration": "هناك مشكلة في التسجيل",
  "error_unregister": "هناك مشكلة في إلغاء التسجيل",
  "do_you_want_to_logout": "هل تريد تسجيل الخروج",
  "present": "حاضر",
  "absent": "غائب",
  "excuse_absent": "غائب بعذر",
  "lag": "لم يسمع",
  "permission": "استأذن",
  "error_set_attendance": "هناك مشكلة ما",
  "date": "التاريخ",
  "there_is_no": "لا يوجد",
  "reset_password": "إعادة تعيين كلمة المرور",
  "complete_the_selection_of_the_course_first_to_display_it_in_the_quran":
      "أكمل اختيار المقرر أولاً لعرضه في المصحف",
  "your_new_password_ok": "تم إرسال كلمة المرور الجديدة إليك في رسالة نصيّة!",
  "agree": "الموافق",
  "late": "متأخر",
  "excellent": "ممتاز",
  "very_good": "جيد جد",
  "good": "جيد",
  "accepted": "مقبول",
  "weak": "ضعيف",
  "general_behavior": "السلوك العام للطالب",
  "activate_offline_work_and_data_synchronization":
      "تفعيل العمل دون اتصال\nومزامنة البيانات",
  "activate": "تفعيل",
  "initializing_loading_data": "جاري تهيئة وتحميل البيانات",
  "episodes_and_students": "الحلقات والطلاب",
  "student_courses": "مقررات الطلاب",
  "educational_plan": "التقارير",
  "all_data_will_be_updated_and_all_unreleased_operations_will_be_cancelled":
      "سوف يتم تحديث كامل البيانات والغاء كل العمليات الغير مرفوعة",
  "student_preparation": "تحضير الطالب",
  "uploadable_data_to_the_server": "البيانات القابلة للرفع الى السيرفر",
  "prepare_students": "تحضير الطلاب",
  "item": "عنصر",
  "general_behavior_students": "السلوك العام للطلاب",
  "behaviors_students": "سلوكيات الطلاب",
  "upload_data": "رفع البيانات",
  "there_are_no_changes_to_upload_to_the_server":
      "لاتوجد تغيرات لرفعها الى السيرفر",
  "do_you_want_to_deactivate_the_offline_work_and_cancel_all_unreleased_operations":
      "هل تريد إلغاء تفعيل العمل دون اتصال والغاء كل العمليات الغير مرفوعة",
  "upload_data_to_the_server": "جاري رفع التغيرات",
  "changes_uploaded_successfully": "تم رفع التغيرات بنجاح",
  "failed_to_upload_changes": "فشل رفع التغيرات",
  "there_are_no_episodes_please_add_one_episode":
      "لا توجد حلقات الرجاء إضافة حلقة واحدة",
  "address": "العنوان",
  "enter_address": "ادخل العنوان",
  "register": "تسجيل",
  "male": "ذكر",
  "female": "أنثى",
  "gender": "الجنس",
  "welcome_with_monitor_episodes": "مرحبا بك في راصد الحلقات",
  "monitor_episodes": "راصد الحلقات",
  "statistics": "الإحصائيات",
  "episodes": "الحلقات",
  "add_episode": "إضافة الحلقات",
  "episode_type": "نوع الحلقة",
  "episode_works": "البرنامج",
  "ok_add": "تم حفظ البيانات بنجاح",
  "there_is_no_students": "لا يوجد طلاب في الحلقه",
  "add_student": "إضافة الطلاب",
  "age": "العمر",
  "enter_age": "أدخل العمر",
  "country": "الدولة",
  "courses_student": "مقررات الطالب",
  "select_one_courses_student": "أختر مقرر واحد على الأقل",
  "number_episodes": "عدد الحلقات",
  "number_students": "عدد الطلاب",
  "operations": "العمليات",
  "students": "الطلاب",
  "most_late_students": "الطلاب الأكثر تاخر",
  "most_absent_students": "الطلاب الأكثر غيابا",
  "most_attended_students": "الطلاب الأكثر حضورا",
  "days": "ايام",
  "episode": "الحلقة",
  "sum_of_the_faces": "مجموع الأوجه في",
  "edit": "تعديل",
  "delete": "حذف",
  "ok_edit": "تم تعديل البيانات بنجاح",
  "ok_delete": "تم حذف بنجاح",
  "edit_episode": "تعديل حلقة",
  "do_you_want_delete": "هل تريد حذف",
  "edit_student": "تعديل طالب",
  "there_is_no_episodes": "لا يوجد حلقات مضافه",
  "do_you_want_to_logout_and_delete_all_data":
      "هل تريد تسجيل الخروج ومسح كل البيانات",
  "there_are_no": "لا يوجد ",
  "search_here": "إبحث هنا",
  "enter_episode": "أدخل الحلقة",
  "create_new_account": "إنشاء حساب جديد",
  "welcom": " مرحباً",
  "username": "اسم المستخدم",
  "enter_username": "أدخل اسم المستخدم ",
  "login": "تسجيل دخول",
  "learn": "حلقة حفظ",
  "learn_review": "حلقة حفظ ومراجعة ",
  "correction": "حلقة تصحيح تلاوة",
  "master": "حلقة اتقان",
  "community": "حلقة جاليات",
  "excellence": "حلقة التميز",
  "review": "حلقة مراجعة",
  "hifz": "الحفظ",
  "mourajaa_s": "المراجعة الصغرى",
  "mourajaa_g": "المراجعة الكبرى",
  "tilawa": "التلاوة",
  "the_episode_cannot_be_deleted_because_there_are_students_in_it":
      "لايمكن حذف الحلقة بسبب وجود طلاب فيها",
  "the_data_has_been_updated_successfully": "تم تحديث البيانات بنجاح",
  "new_update_is_available": "يتوفر تحديث جديد للبيانات",
  "student_episode_data_is_being_updated":
      "تم تحديث بيانات الطلاب في النظام.\n الرجاء الضغط على ( مزامنة ) لعكس التحديثات في التطبيق.",
  "student_attendances_episode_data_is_being_updated":
      "تم تحديث بيانات الطالب في النظام.\n الرجاء الضغط على ( مزامنة ) لعكس التحديثات في التطبيق.",
  "episode_data_is_being_updated":
      "تم تحديث بيانات الحلقات في النظام.\n الرجاء الضغط على ( مزامنة ) لعكس التحديثات في التطبيق.",
  "sync": "مزامنة",
  "the_student_cannot_be_deleted_because_it_is_linked_to_a_memorization_plan":
      "لايمكن حذف الطالب لانه مربوط بخطة حفظ أو مراجعة",
  "settings": 'إعدادات',
  "language": 'اللغة',
  "delete_account": "حذف الحساب",
  "confirm_delete_account": "هل انت متاكد من حذف الحساب وجميع البيانات",
  "password_recovery": "استرجاع كلمة المرور",
  "send": "إرسال",
  "verification": "تَحَقّق",
  "enter_your_code_number": "أدخل رقم التحقق الخاص بك",
  "verify": "تأكيد",
  "resend_new_code": "إعادة إرسال رمز جديد",
  "new_password": "تحديث كلمة المرور",
  "verification_code_has_timed_out": "انتهت مهلة رمز التحقق",
  "verification_code_is_incorrect": "رمز التحقق غير صحيح",
  "erorr_happened": "حدث خطأ من فضلك حاول مرة أخرى",
  "update_app": "تتوفر نسخة جديدة من التطبيق",
  "update": "قم بالتحديث الآن",
};
