Map<String, String> translateArabic = {
  "title": "Usteps",
  "logout": "تسجيل خروج",
  "please_wait": " الرجاء الانتظار ...",
  "sign_in": "تسجيل دخول",
  "email": "البريد الإلكتروني",
  "email_error": "البريد الإلكتروني خاطئ",
  "enter_email": "أدخل البريد الاكتروني",
  "password": "كلمة المرور",
  "enter_password": "أدخل كلمة المرور",
  "welcome_back": "أهلا بعودتك",
  "forgot_password": "نسيت كلمة المرور؟",
  "use_password": "استخدام كلمة المرور",
  "scan_your_fingerprint_to_authenticate": "امسح بصمة إصبعك للمصادقة",
  "authentucation_required": "المصادقة مطلوبة",
  "verify_identity": "تحقق من الهوية",
  "notifications": "الإشعارات",
  "login_first_with_password": "سجل دخول اولآ باستخدام كلمة المرور",
  "there_is_no_fingerprint_on_your_device": "لا توجد بصمة في جهازك",
  "more": "المزيد",
  "error_connect_to_netwotk": "لا يوجد اتصال بالانترنت",
  "error_connect_to_server": "مشكله في الاتصال بالسيرفر",
  "url_connect_be_found": "اممم... هذه الصفحة غير موجودة.",
  
  
  "Log_in_and_enjoy": "قم بتسجيل الدخول واستمتع",
  "nice_walk": "بنزهة جميلة",
  "join_the_eden_pearl_park_and_pools_family": "انضم إلى عائلة منتزه ومسابح لؤلؤة عدن",
  "by_creating_a_new_account": "بــ  إنشاء حساب جديد",
  "welcome_with_family": "مرحبا بك مع عائلة",
  "the_pearl_of_eden_park_and_swimming_pools": "منتزه ومسابح لؤلؤة عدن",
  "name": "الاسم",
  "enter_name": "أدخل الاسم",
  "phone": "رقم الجوال",
  "enter_phone": "أدخل رقم الجوال",
  "enter_a_9_digit_number": "أدخل رقم جوال مكون من ٩ ارقام",
  "copy_of_the_passport_card": "صورة الجواز / البطاقة",
  "enter_copy_of_the_passport_card": "أدخل صورة الجواز / البطاقة",
  "construction": "إنشاء",
  "if_you_have_an_account_just": "إذا عندك حساب فقط قم",
  "sign_up": "بــ  تسجيل الدخول",
  "verification_code": "رمز التحقق",
  "enter_the_verification_code_sent_to_your_email": "قم بإدخال الرمز التحقق المرسل إلى بريدك",
  "resend_code": "إعادة ارسال الرمز",
  "accent": "تاكيد",
  "restore_password": "استعادة كلمة المرور",
  "forgot_your_password": "نسيت كلمة المرور",
  "submit": "ارسال",
  "verification_code_will_be_sent": "سيتم ارسال كود للتحقق",
  "from_the_health_of_the_account_owner_via_email": "من صحة مالك الحساب عبر البريد الإلكتروني",
  "create_a_new_password": "إنشاء كلمة مرور جديدة",
  "by_create_a_new_password": "قم بإنشاء كلمة مرور جديدة",
  "new_password": "كلمة المرور الجديدة",
  "enter_new_password": "أدخل كلمة المرور الجديدة",
  "beautiful_look_and_outfit": "إطلالة وحلة جميلة",
  "completely_different_from_all": "مختلفة تماماً عن الكل",
  "available_periods": "الفترات المتاحة",
  "morning": "الصباح",
  "everyDay": "كل اليوم",
  "evening": "المساء",
  "add": "إضافة",
  "camera": "كاميرا",
  "gallery": "المعرض",
  "instructions_before_booking": "تعليمات  قبل الحجز",
  "period_details": "تفاصيل الفترة",
  "period": "الفترة",
  "price": "السعر",
  "start": "تبدأ",
  "end": "تنتهي",
  "afternoon": "عصراً",
  "a.m": "صباحاً",
  "p.m": "مساءً",
  "book_now": "أحجز الآن",
  "terms_and_obligation": "شروط وإلتزامات",
  "terms_and_conditions_that_you_must_read_before_booking": "أحكام وشروط عليك قراءتها قبل الحجز",
  "agree_to_the_terms": "أوافق على الشروط",
  "agree_and_confirm_to_be_bound_by_these_terms": "أوافق وأوكد على الالتزام بهذه الشروط",
  "complete_your_reservation": "استكمال الحجز",
  "our_account_at_the_cashiers": "حسابتنا عند الصرافين",
  "account_name": "اسم الحساب | ",
  "choose_your_money_changer": "أختر صرافك وقم بإيداع قسط او كامل\nالمبلغ لتأكيد الحجز",
  "name_of_the_depositor": "اسم مودع المبلغ",
  "please_write_the_name_of_the_person_depositing": "يرجى كتابة اسم الشخص المودع",
  "attach_the_receipt_voucher": "ارفق سند الإيصال",
  "enter_attach_the_receipt_voucher": "يرجئ ارفق سند الإيصال",
  "reservation_confirmation": "تأكيد الحجز",
  "choose_your_cashier_and_deposit_a_premium_or_full_amount_to_confirm_the_reservation": "أختر صرافك وقم بإيداع قسط او كامل\nالمبلغ لتأكيد الحجز",
  "enter_name_of_the_depositor": "يرجئ كتابة اسم الشخص المودع",
  "hello": "أهلاً وسهلاً بك",
  "sign_in_to_book_view_your_order_list": "قم بتسجيل الدخول للحجز\nوعرض قائمة طلباتك",
  "about_the_pearl_of_eden": "عن لؤلؤة عدن",
  "stay_with_us_first_on_our_account": "خليك معنا أول بأول حسابتنا على",
  "list_of_orders": "قائمة الطلبات",
  "under_revision": "تحت المراجعة",
  "canceled": "ملغي",
  "acceptable": "مقبول",
  "complete_the_amount": "إستكمال المبلغ",
  "cancelling_order": "إلغاء الطلب",
  "save_changed": "حفظ التغيرات",
  "our_ads": "إعلاناتنا",

  "identification_number_location":"رقم الهوية / الاقامة",
  "enter_identification_number_location":"أدخل رقم الهوية / الاقامة",
  "episode_list":"قائمة الحلقات",
  "maknoon":"مكنون",
  "synchronization":"مزامنة البيانات",
  "suggestions_and_complaints":"المقترحات و الشكاوي",
  "about_as":"من نحن",
  "draft":"حاضر",
  "done":"اكمل",
  "follow_up":"المتابعة",
  "listen":"الحفظ",
  "reviewsmall":"المراجعة الصغرى",
  "reviewbig":"المراجعة الكبرى",
  "tlawa":"التلاوة",
  "quran":"المصحف",
  "from_sura":"من سورة",
  "from_aya":"من آية",
  "to_sura":"إلى سورة",
  "to_aya":"إلى آية",
  "course":"المقرر",
  "Notes":"الملاحظات",
  "save_errors":"أخطاء الحفظ",
  "preservation_quality":"جودة الحفظ",
  "intonation_errors":"أخطاء التجويد",
  "date_planned":"تاريخ الأستحقاق",
  "actual_date":"تاريخ التسليم",
  "difference_date":"الفرق",
  "day":"يوم",
  "enter_number":"ادخل الرقم",
  "save":"حفظ",
  "can_not_yong_surh":"لا يمكن اختيار سورة ترتيبها أسفل",
  "can_not_up_surh":"لا يمكن اختيار سورة ترتيبها أعلى",
  "can_not_bottom_aya":"لا يمكن اختيار اية ترتيبها أسفل",
  "can_not_up_aya":"لا يمكن اختيار اية ترتيبها أعلى",
  "warring":"تنبيه",
  "ok_add_listen_line":"تم حفظ البيانات بنجاح",
  "error_add_listen_line":"هناك مشكلة في إضافة مقرر",
  "behaviour":"السلوك",
  "behaviour_student":"إضافة سلوك للطالب",
  "note_behaviour_student":"ملاحظات السلوك السابقة",
  "select_behaviour":"اختر سلوك",
  "do_you_want_to_send_the_behavior":"هل تريد إرسال السلوك",
  "inform_the_parent_of_the_behavior":"ابلاغ ولي الامر بالسلوك",
  "send_the_behavior_to_the_episode_moderator":"إرسال السلوك لمشرف الحلقة",
  "yes":"نعم",
  "no":"لا",
  "confirm":"تاكيد",
  "ok_add_behavior":"تم إضافة السلوك بنجاح",
  "error_add_behavior":"هناك مشكلة في إضافة سلوك",
  "there_is_no_notes":"لاتوجد ملاحظات",
  "there_is_no_notifications":"لاتوجد اشعارات",
  "notification_details":"تفاصيل الاشعار",
  "notification_date":"تاريخ الاشعار",
  "ok":"موافق",
  "subject_of_complaint":"موضوع الشكوى",
  "complaint_details":"تفاصيل الشكوى",
  "enter_subject":"ادخل موضوع الشكوى",
  "enter_details":"ادخل تفاصيل الشكوى",
  "studentـnomination":"ترشيح طالب",
  "select_period":"اختر فتره",
  "select_center":"اختر مركز",
  "there_is_no_calendarCenter":"لا توجد جداول للاختبارات",
  "center_test":"مركز الاختبار",
  "type":"النوع",
  "path":"المسار",
  "branch":"الفرع",
  "error_get_branches":"هناك مشكلة في تحميل الفروع",
  "registration":"تسجيل",
  "unregister":"إلغاء تسجيل",
  "ok_registration":"تم التسجيل بنجاح",
  "ok_unregister":"تم إلغاء التسجيل بنجاح",
  "error_registration":"هناك مشكلة في التسجيل",
  "error_unregister":"هناك مشكلة في إلغاء التسجيل",
  "do_you_want_to_logout":"هل تريد تسجيل الخروج",
  "present":"حاضر",
  "absent":"غائب",
  "absent_excuse":"غائب بعذر",
  "not_read":"لم يسمع",
  "excuse":"استأذن",
  "error_set_attendance":"هناك مشكلة ما",
  "date":"التاريخ",
  "there_is_no":"لا يوجد",
  "reset_password":"إعادة تعيين كلمة المرور",
  "complete_the_selection_of_the_course_first_to_display_it_in_the_quran":"أكمل اختيار المقرر أولاً لعرضه في المصحف",
  "your_new_password_ok":"تم إرسال كلمة المرور الجديدة إليك في رسالة نصيّة!",
  "agree":"الموافق",
  "delay":"متأخر",
  "excellent" : "ممتاز",
  "very_good" : "جيد جد",
  "good" : "جيد",
  "accepted" : "مقبول",
  "weak" : "ضعيف",
  "general_behavior" : "السلوك العام للطالب",
  "activate_offline_work_and_data_synchronization" : "تفعيل العمل دون اتصال\nومزامنة البيانات",
  "activate":"تفعيل", 
  "initializing_loading_data":"جاري تهيئة وتحميل البيانات",
  "episodes_and_students":"الحلقات والطلاب",
  "student_courses":"مقررات الطلاب",
  "educational_plan":"التقارير",
  "all_data_will_be_updated_and_all_unreleased_operations_will_be_cancelled":"سوف يتم تحديث كامل البيانات والغاء كل العمليات الغير مرفوعة",
  "student_preparation":"تحضير الطالب",
  "uploadable_data_to_the_server":"البيانات القابلة للرفع الى السيرفر",
  "prepare_students":"تحضير الطلاب",
  "item":"عنصر", 
  "general_behavior_students":"السلوك العام للطلاب", 
  "behaviors_students":"سلوكيات الطلاب",
  "upload_data":"رفع البيانات",
  "there_are_no_changes_to_upload_to_the_server":"لاتوجد تغيرات لرفعها الى السيرفر",
  "do_you_want_to_deactivate_the_offline_work_and_cancel_all_unreleased_operations":"هل تريد إلغاء تفعيل العمل دون اتصال والغاء كل العمليات الغير مرفوعة",
  "upload_data_to_the_server":"جاري رفع التغيرات",
  "changes_uploaded_successfully":"تم رفع التغيرات بنجاح",
  "failed_to_upload_changes":"فشل رفع التغيرات",
  "there_are_no_episodes_please_add_one_episode":"لا توجد حلقات الرجاء إضافة حلقة واحدة",
  "address":"العنوان",
  "enter_address":"ادخل العنوان",
  "register":"تسجيل",
  "male":"ذكر",
  "female":"أنثى",
  "gender":"الجنس",
  "welcome_with_monitor_episodes": "مرحبا بك في راصد الحلقات",
  "monitor_episodes": "راصد الحلقات",
  "statistics": "الإحصائيات",
  "episodes":"الحلقات",
  "add_episode":"أضافة حلقة",
  "episode_type":"نوع الحلقة",
  "episode_works":"البرنامج",
   "ok_add":"تم حفظ البيانات بنجاح",
   "there_is_no_students":"لا يوجد طلاب في الحلقه",
   "add_student":"أضافة طالب",
   "age": "العمر",
  "enter_age": "أدخل العمر",
  "country": "الدولة",
  "courses_student":"مقررات الطالب",
  "select_one_courses_student":"أختر مقرر واحد على الأقل",
  "number_episodes":"عدد الحلقات",
  "number_students":"عدد الطلاب",
  "operations":"العمليات",
  "students":"الطلاب",
  "most_late_students":"الطلاب الأكثر تاخر",
  "most_absent_students":"الطلاب الأكثر غيابا",
  "most_attended_students":"الطلاب الأكثر حضورا",
  "days":"ايام",
  "episode":"الحلقة",
  "sum_of_the_faces":"مجموع الأوجه في",
  "edit":"تعديل",
  "delete":"حذف",
  "ok_edit":"تم تعديل البيانات بنجاح",
  "ok_delete":"تم حذف بنجاح",
  "edit_episode":"تعديل حلقة",
  "do_you_want_delete":"هل تريد حذف",
  "edit_student":"تعديل طالب",
  "there_is_no_episodes":"لا يوجد حلقات مضافه",
  "do_you_want_to_logout_and_delete_all_data":"هل تريد تسجيل الخروج ومسح كل البيانات",
  "there_are_no": "لا يوجد ",
  "search_here" :"إبحث هنا", 
  "enter_episode": "أدخل الحلقة",
};  
   
 
   
   
