Map<String, String> translateEnglish = {
  "title": "Halaqat Monitor",
  "logout": "Logout",
  "please_wait": "Please wait ...",
  "sign_in": "Sign In",
  "email": "E-mail",
  "email_error": "wrong email",
  "enter_email": "Enter E-mail",
  "password": "Password",
  "enter_password": "Enter password",
  "welcome_back": "welcome back",
  "forgot_password": "Forgot password?",
  "use_password": "Use password",
  "error_connect_to_netwotk": "No internet connection",
  "error_connect_to_server": "Problem connecting to the server",
  "url_connect_be_found": "This page not found",
  "name": "Name",
  "enter_name": "Enter the name",
  "phone": "Mobile number",
  "enter_phone": "Enter mobile number",
  "construction": "Create",
  "sign_up": "Sign Up",
  "add": "Add",
  "save_changed": "Save changed",
  "identification_number_location": "Identification number / Location",
  "enter_identification_number_location":
      "Enter identification number / Location",
  "episode_list": "Episode list",
  "maknoon": "Maknoon",
  "synchronization": "Data Synchronization",
  "suggestions_and_complaints": "Suggestions and Complaints",
  "about_as": "About us",
  "draft": "attende",
  "done": "Done",
  "follow_up": "Follow-up",
  "listen": "Hifz",
  "reviewsmall": "Review small",
  "reviewbig": "Review big",
  "tlawa": "Recitation",
  "quran": "Quran",
  "from_sura": "From surah",
  "from_aya": "From ayah",
  "to_sura": "To surah",
  "to_aya": "To ayah",
  "course": "Course",
  "Notes": "Notes",
  "save_errors": "Save errors",
  "preservation_quality": "Preservation quality",
  "intonation_errors": "Intonation errors",
  "date_planned": "due date",
  "actual_date": "delivery date",
  "difference_date": "The difference",
  "day": "Day",
  "enter_number": "Enter the number",
  "save": "Save",
  "can_not_yong_surh":
      "It is not possible to choose a surah with a lower order",
  "can_not_up_surh": "It is not possible to select a surah of a higher order",
  "can_not_bottom_aya":
      "It is not possible to choose a ayah with a lower order",
  "can_not_up_aya": "It is not possible to select a ayah of a higher order",
  "warring": "Warring",
  "ok_add_listen_line": "Data saved successfully",
  "error_add_listen_line": "There was a problem adding a course",
  "behaviour": "Behaviour",
  "behaviour_student": "Add Student Behavior",
  "note_behaviour_student": "Previous Behavior Notes",
  "select_behaviour": "Select behaviour",
  "do_you_want_to_send_the_behavior": "Do you want to send the behavior",
  "inform_the_parent_of_the_behavior": "Inform the guardian of the behavior.",
  "send_the_behavior_to_the_episode_moderator":
      "Send the behavior to the episode moderator",
  "yes": "Yes",
  "no": "No",
  "confirm": "Confirm",
  "ok_add_behavior": "Behavior added successfully",
  "error_add_behavior": "There is a problem to add behavior",
  "there_is_no_notes": "There is no notes",
  "there_is_no_notifications": "No notifications found",
  "notification_details": "Notification details",
  "notification_date": "Notification date",
  "ok": "Ok",
  "subject_of_complaint": "Subject of complaint",
  "complaint_details": "Complaint details",
  "enter_subject": "Enter the subject of the complaint",
  "enter_details": "Enter the details of the complaint",
  "studentـnomination": "Student nomination",
  "select_period": "Select period",
  "select_center": "Select center",
  "there_is_no_calendarCenter": "There are no exam schedules",
  "center_test": "Test center",
  "type": "Type",
  "path": "Path",
  "branch": "Branch",
  "error_get_branches": "There was a problem loading branches",
  "registration": "Registration",
  "unregister": "Unregister",
  "ok_registration": "successfully registered",
  "ok_unregister": "Registration cancelled successfully",
  "error_registration": "There is a problem registering",
  "error_unregister": "There was a problem canceling the registration",
  "do_you_want_to_logout": "Do you want to log out?",
  "present": "attende",
  "absent": "Absent",
  "excuse_absent": "excused absent",
  "lag": "Not reading",
  "permission": "Permission",
  "error_set_attendance": "something is wrong",
  "date": "Date",
  "there_is_no": "nothing",
  "reset_password": "Reset password",
  "complete_the_selection_of_the_course_first_to_display_it_in_the_quran":
      "Complete the selection of the course first to display it in the quran",
  "your_new_password_ok":
      "Your new password has been sent to you in a text message!",
  "agree": "Agree",
  "late": "Late",
  "excellent": "Excellent",
  "very_good": "Very good",
  "good": "Good",
  "accepted": "Acceptable",
  "weak": "Weak",
  "general_behavior": "General behavior of the student",
  "activate_offline_work_and_data_synchronization":
      "Enable Offline Work\nand Data Sync",
  "activate": "Activate",
  "initializing_loading_data": "Initializing and loading data",
  "episodes_and_students": "Episodes and students",
  "student_courses": "Student courses",
  "educational_plan": "reports",
  "all_data_will_be_updated_and_all_unreleased_operations_will_be_cancelled":
      "All data will be updated and all un-uploaded operations will be cancelled.",
  "student_preparation": "Student preparation",
  "uploadable_data_to_the_server": "Uploadable data to the server",
  "prepare_students": "Prepare students",
  "item": "Item",
  "general_behavior_students": "General behavior of students",
  "behaviors_students": "Behaviors students",
  "upload_data": "Upload data",
  "there_are_no_changes_to_upload_to_the_server":
      "There are no changes to upload to the server.",
  "do_you_want_to_deactivate_the_offline_work_and_cancel_all_unreleased_operations":
      "Do you want to deactivate offline work and cancel all unmounted operations?",
  "upload_data_to_the_server": "Upload changes",
  "changes_uploaded_successfully": "Changes uploaded successfully",
  "failed_to_upload_changes": "Failed_to_upload_changes",
  "there_are_no_episodes_please_add_one_episode":
      "There are no episodes please add one episode",
  "address": "Address",
  "enter_address": "Enter address",
  "register": "Register",
  "male": "Male",
  "female": "Female",
  "gender": "Gender",
  "welcome_with_monitor_episodes": "Welcome with monitor episodes",
  "monitor_episodes": "Monitor episodes",
  "statistics": "Statistics",
  "episodes": "Episodes",
  "add_episode": "Add episode",
  "episode_type": "Episode type",
  "episode_works": "Episode works",
  "ok_add": "Data saved successfully",
  "there_is_no_students": "There are no students in the episode",
  "add_student": "Add student",
  "age": "Age",
  "enter_age": "Enter Age",
  "country": "Country",
  "courses_student": "Courses student",
  "select_one_courses_student": "Choose at least one course",
  "number_episodes": "Number of episodes",
  "number_students": "number of students",
  "operations": "Operations",
  "students": "Students",
  "most_late_students": "The most late students",
  "most_absent_students": "most absent students",
  "most_attended_students": "Most attended students",
  "days": "Days",
  "episode": "Episode",
  "sum_of_the_faces": "Sum of faces in",
  "edit": "Edit",
  "delete": "Delete",
  "ok_edit": "Data modified successfully",
  "ok_delete": "deleted successfully",
  "edit_episode": "Edit episode",
  "do_you_want_delete": "Do you want delete",
  "edit_student": "Edit student",
  "there_is_no_episodes": "There are no episodes added",
  "do_you_want_to_logout_and_delete_all_data":
      "Do you want to log out and delete all data?",
  "there_are_no": "Nothing",
  "search_here": "Search here",
  "enter_episode": "Enter episode",
  "create_new_account": "Create new account",
  "welcom": " Welcom",
  "username": "User name",
  "enter_username": "Enter user name",
  "login": "Login",
  "learn": "Learn episode",
  "learn_review": "Learn and review episode",
  "correction": "Recitation correction episode",
  "master": "mastery episode",
  "community": "Community episode",
  "excellence": "Excellence episode",
  "review": "Review episode",
  "hifz": "Hifz",
  "mourajaa_s": "Review small",
  "mourajaa_g": "Review big",
  "tilawa": "recitation",
  "the_episode_cannot_be_deleted_because_there_are_students_in_it":
      "The episode cannot be deleted because there are students in it",
  "the_data_has_been_updated_successfully": "Data updated successfully",
  "new_update_is_available": "New data update available.",
  "student_episode_data_is_being_updated":
      "Students' data has been updated in the system.\n Please press (sync) to reflect the updates in the application.",
  "student_attendances_episode_data_is_being_updated":
      "The student's data has been updated in the system.\n Please press (sync) to reflect the updates in the application.",
  "episode_data_is_being_updated":
      "The episode data has been updated in the system.\nPlease press (sync) to reflect the updates in the application.",
  "sync": "Sync",
  "the_student_cannot_be_deleted_because_it_is_linked_to_a_memorization_plan":
      "The student cannot be deleted because he is linked to a memorization or revision plan",
  "settings": 'Settings',
  "language": 'Language',
  "delete_account": "Delete account",
  "confirm_delete_account": "Are you sure to delete the account and data?",
};
