// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCaC3bq3CHv53uZRLgwUmbiQPmxr3gqkY',
    appId: '1:1013092210635:android:46fdccdfccee941ce6084e',
    messagingSenderId: '1013092210635',
    projectId: 'monitor-episodes',
    databaseURL: 'https://monitor-episodes-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'monitor-episodes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrwxByNN9lfnTGlA_eifqkybUZZsUxL5s',
    appId: '1:1013092210635:ios:05dc118540309891e6084e',
    messagingSenderId: '1013092210635',
    projectId: 'monitor-episodes',
    databaseURL: 'https://monitor-episodes-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'monitor-episodes.appspot.com',
    iosClientId: '1013092210635-ocu4pjj391q24tcefet2mftimu5n059e.apps.googleusercontent.com',
    iosBundleId: 'com.example.monitorEpisodes',
  );
}
